services:
  python:
    image: python:alpine
    build:
      context: .
      dockerfile: ./python.Dockerfile
    ports:
      - "5000:5000"
  
  node:
    image: node:alpine
    build:
      context: .
      dockerfile: ./node.Dockerfile
    ports:
      - "3000:3000"
  
  go:
    image: go
    build:
      context: .
      dockerfile: ./go.Dockerfile
    ports:
      - "8080:8080"